version: '3.8'

services:
  backend:
    image: ghcr.io/JenikBranik/dashboard-backend:latest
    container_name: dashboard-backend
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - TZ=Europe/Prague
    
  frontend:
    image: ghcr.io/JenikBranik/dashboard-frontend:latest
    container_name: dashboard-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
