name: CD backend

on:
  push:
    branches: [main]
    paths:
      - 'src/backend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: JenikBranik/dashboard-backend

jobs:
  backend-cd:
    runs-on: [ubuntu-latest]
    environment: dev
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: src/backend
        push: true
        tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}

    - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy na Debian server pres Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          echo "[vps_servers]" > inventory.ini
          echo "${{ secrets.SERVER_IP }} ansible_user=jenda" >> inventory.ini
          
          ansible-playbook -i inventory.ini ansible/playbooks/deploy.yml