name: CD frontend

on:
  push:
    branches: [main]
    paths:
    - 'src/frontend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jenikbranik/dashboard-frontend

jobs:
  frontend-cd:
    runs-on: [ubuntu-latest]
    environment: dev
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to repository
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: src/frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
        
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          add-identity: true

      - name: Deploy na Debian server pres Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i inventory.ini ansible/playbooks/deploy.yml -e "github_username=${{ github.actor }} github_token=${{ secrets.GHCR_TOKEN }}"
